name: Build on macOS
on:
  workflow_dispatch:
  push:
    paths: 'firmware/**'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  PROJECT_NAME: rp27c512
  PROJECT_DIR: $PROJECT_NAME/firmware
  BUILD_TYPE: Release
  PICO_SDK_VERSION: 2.0.0
  PICO_BOARD: pico
  NPROC: 3

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Clean workspace
        run: |
          echo "Cleaning up previous run"
          rm -rf "${{ github.workspace }}"
          mkdir -p "${{ github.workspace }}"

      - name: Checkout ${{ env.PROJECT_NAME }}
        uses: actions/checkout@v4
        with:
          path: ${{ env.PROJECT_NAME }}

      - name: Checkout pico-sdk
        uses: actions/checkout@v4
        with:
          repository: raspberrypi/pico-sdk
          ref: ${{ env.PICO_SDK_VERSION }}
          path: pico-sdk

      - name: Checkout pico-sdk submodules
        working-directory: ${{ github.workspace }}/pico-sdk
        run: git submodule update --init

      - name: Install dependencies
        run: |
          brew install cmake
          brew install --cask gcc-arm-embedded

      - name: Build Project
        working-directory: ${{github.workspace}}/${{ env.PROJECT_DIR }}
        shell: bash
        run: |
          mkdir build
          cd build
          cmake .. -G "Unix Makefiles" -DPICO_SDK_PATH=../../pico-sdk -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DPICO_BOARD=${{ env.PICO_BOARD }}
          cmake --build . --parallel ${{ NPROC }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: ${{ env.PROJECT_DIR }}/build/*.uf2
